spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkgame?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
